### ISSUE TITLE
[Milestone 1 Submission]: 

### ISSUE THREAD

**Issue by Edoumou** [toposware/topos-builders-program#24]
### Project title

Financial Bonds Tokenization

### Link to grant application issue

https://github.com/toposware/topos-builders-program/issues/4

### Milestone submission

Milestone Number: 1

Milestone Summary: Choice of the tools to be used: React, Truffle or Hardhat, Programming language probably Solidity, etc... Start Modelling the Bond Token with all its characteristics like the issue date, the principal, the interest rate, or the maturity date. Create the Bond Token contract and implement the registration of issuers and investors. Implement the deal submission and validation

Milestone Timeframe: 1 week

### Link to the open-source code/delivery

https://github.com/Edoumou/T-Grant

### License

APACHE2

### Any additional information

The project uses Truffle, and the Topos subnet client is launched through Ganache. The `README` file shows the full process of running the Decentralized Application.

All the tasks that have been proposed for the Milestone 1 have been implemented (smart contract integration).

- [x] Choice of the tools to be used: React, Truffle or Hardhat, Programming language probably Solidity, etc.
- [x] Start Modelling the Bond Token with all its characteristics like the issue date, the principal, the interest rate, or the maturity date
- [x] Create the Bond Token contract and implement the registration of issuers and investors
- [x] Implement the deal submission and validation

**Comment by Edoumou** [comment]
Here are some interesting links for the project:

- https://github.com/users/Edoumou/projects/3/views/1?pane=issue&itemId=43288637
- https://github.com/Edoumou/T-Grant/issues
- https://github.com/Edoumou/T-Grant/pulls

**Comment by Edoumou** [comment]
The migration from Truffle to Hardhat as asked by Topos team has been done successfully.

https://github.com/Edoumou/T-Grant/commit/ee88a4ae69b2403851b1e6b1faf90a86f64dd82e
